jobs:
  typecheck:
    name: ʦ Typecheck
    runs-on: ubuntu-latest
    steps:
    - name: ⬇️ Checkout repo
      uses: actions/checkout@v4
    - name: 🐣 Install Pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8
    - name: ⎔ Setup Node.JS
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'pnpm'
    - name: 📥 Install deps
      run: pnpm install
    - name: 🔎 Type Check
      run: pnpm typecheck